### ISSUE TITLE
Import and clean test data by REST APIs

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/blackbox-testing#113]
Import and clean test data by REST APIs instead of MongoDB scripts.

**Comment by tsconn23** [comment]
Keep in mind the discussions we've had that indicate the practice of seeding data to drive tests is short-lived. This is because we cannot support a data import strategy for any number of data providers that may want to integrate with us (Mongo, Redis, ObjectBox, etc). Therefore tests need to be independent and sequenced in such a way that they create their own data.

I'm dubious of the long term value of assigning much effort to this issue.

**Comment by cloudxxx8** [comment]
@tsconn23 We fixed this issue by seeding test data via general EdgeX Rest API, so it can support any other data providers.  It is independent now.
