### ISSUE TITLE
Some failed test cases in security black box test

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/blackbox-testing#179]
@tingyuz, Please help take a look the failed test cases of security black box test when you have time.
Thanks.
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-centos7-blackbox-4c-2g-master/allure/
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-master/allure/

**Comment by tingyuz** [comment]
It's interesting... Here is the result I just ran on my testing environment without such errors:

security-service-docker

❏ apigateway / Health Check
↳ 01 port 8000 missing token test
  GET http://kong:8000/coredata/api/v1/ping [401 Unauthorized, 306B, 104ms]
  ✓  Port 8000 with missing token test

↳ 02 port 8001 admin port test
  GET http://kong:8001/ [200 OK, 5.13KB, 7ms]
  ✓  Port 8001 served
  ✓  Has Content-Type
  ✓  Content-Type is application/json

↳ 03 port 8443 non-existing path test
  GET https://kong:8443/ [404 Not Found, 241B, 33ms]
  ✓  Port 8443 not served

↳ 04 port 8443 SSL missing token test
  GET https://kong:8443/coredata/api/v1/ping [401 Unauthorized, 306B, 3ms]
  ✓  Port 8443 with missing token test

↳ 05 port 8444 SSL admin port test
  GET https://kong:8444/ [200 OK, 5.13KB, 13ms]
  ✓  Port 8444 served
  ✓  Has Content-Type
  ✓  Content-Type is application/json

❏ apigateway / Proxy Check
↳ 01 Unauthorized token proxy access test
  GET https://kong:8443/coredata/api/v1/ping [401 Unauthorized, 306B, 3ms]
  ✓  Unauthorized Access Failure

↳ 02 valid token proxy access test coredata
  GET https://kong:8443/coredata/api/v1/ping [200 OK, 217B, 419ms]
  ✓  Valid token access success
  ✓  Has Content-Type
  ✓  Content-Type is text/plain
  ✓  Body is correct

↳ 03 invalid token proxy access test metadata - OauthToken test
  GET https://kong:8443/metadata/api/v1/ping [401 Unauthorized, 404B, 34ms]
  ✓  Unauthorized token access failure test

↳ 04 reading error test
  PUT https://kong:8443/coredata/api/v1/reading [404 Not Found, 292B, 21ms]
  ✓  Status code is 404

↳ 05 POST reading test
  POST https://kong:8443/coredata/api/v1/reading [200 OK, 248B, 12ms]
  ✓  Status code is 200
  ✓  Has Content-Type
  ✓  Content-Type is text/plain

❏ secretstore
↳ 01 health check
  GET https://edgex-vault:8200/v1/sys/health [200 OK, 401B, 30ms]
  ✓  Secret store health check
  ✓  Has Content-Type
  ✓  Content-Type is application/json
  ✓  Vault is inited
  ✓  Vault is unsealed

↳ 02 mising vault keytest
  GET https://edgex-vault:8200/v1/sys/key-status [400 Bad Request, 178B, 3ms]
  ✓  Missing secret store access check
  ✓  Has Content-Type
  ✓  Content-Type is application/json
  ✓  Missing token error

↳ 03 unauthorized vault key test
  GET https://edgex-vault:8200/v1/sys/key-status [403 Forbidden, 173B, 17ms]
  ✓  Unauthorized secret store access check
  ✓  Has Content-Type
  ✓  Content-Type is application/json
  ✓  Permission denied test

↳ 04 valid vault key test
  GET https://edgex-vault:8200/v1/sys/key-status [200 OK, 403B, 3ms]
  ✓  Unauthorized secret store access check
  ✓  Has Content-Type
  ✓  Content-Type is application/json
  ✓  vault key term test

┌─────────────────────────┬──────────┬──────────┐
│                         │ executed │   failed │
├─────────────────────────┼──────────┼──────────┤
│              iterations │        1 │        0 │
├─────────────────────────┼──────────┼──────────┤
│                requests │       14 │        0 │
├─────────────────────────┼──────────┼──────────┤
│            test-scripts │       28 │        0 │
├─────────────────────────┼──────────┼──────────┤
│      prerequest-scripts │       14 │        0 │
├─────────────────────────┼──────────┼──────────┤
│              assertions │       36 │        0 │
├─────────────────────────┴──────────┴──────────┤
│ total run duration: 1710ms                    │
├───────────────────────────────────────────────┤
│ total data received: 10.89KB (approx)         │
├───────────────────────────────────────────────┤
│ average response time: 50ms                   │
└───────────────────────────────────────────────┘

**Comment by tingyuz** [comment]
This was due to a bug introduced in #171. I have #180 to fix it and pending for verification.

**Comment by cloudxxx8** [comment]
the failed test cases still exist
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-centos7-blackbox-4c-2g-master/allure/

**Comment by tingyuz** [comment]
Just took a look at the Jenkins log and it appears that there are some testing cases failed last night in job 43.

https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-centos7-blackbox-4c-2g-master/43/console

However the testing cases are all successful in the latest job 44.

https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-centos7-blackbox-4c-2g-master/44/console


taking a close look at the failed case in job 43 and noticed that the testing cases were failed due to the upstream microservices  ( coredata and metada) unavailable at that time.  Here is one sample failed test case.

08:41:20 security-service-docker
08:41:20
08:41:20 ❏ apigateway / Health Check
08:41:20 ↳ 01 port 8000 missing token test
08:41:20   GET http://kong:8000/coredata/api/v1/ping [404 Not Found, 241B, 120ms]
08:41:21   1. Port 8000 with missing token test

For the testing to be successful ( as a proxy) the upstream services need to be up. And it seems in job 44 the microservice are up and the test case is successful. Here is the log in job 44.


08:40:31 security-service-docker

08:40:31

08:40:31 ❏ apigateway / Health Check

08:40:31 ↳ 01 port 8000 missing token test

08:40:31   GET http://kong:8000/coredata/api/v1/ping [401 Unauthorized, 306B, 105ms]

08:40:31   ✓  Port 8000 with missing token test


Thanks,
Tingyu

**Comment by cloudxxx8** [comment]
security test passed on x86, thanks, @tingyuz
