### ISSUE TITLE
Add test for querying limited transmission with specified slug and date range 

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/blackbox-testing#232]
Test GET API `/transmission/slug/{slug}/start/{start}/end/{end}/{limit}`
Original issue https://github.com/edgexfoundry/edgex-go/issues/1335

**Comment by tsconn23** [comment]
@weichou1229 @cloudxxx8 Re-opening this issue due to apparent test failure in [Allure report](https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-centos7-blackbox-4c-2g-master/allure/#suites/dd3bcc6dd0938274ae8345a155a4e8af) this morning.

<img width="760" alt="Screen Shot 2019-05-23 at 9 53 07 AM" src="https://user-images.githubusercontent.com/1342980/58263029-f1d29700-7d40-11e9-827a-1156f4e9cb12.png">

**Comment by weichou1229** [comment]
I test on my side, but it works fine. I thought the docker image is not updated before the test run. 
I will check the test result after the Jenkins run test again. 

```
cd path/to/blackbox-testing
source ./bin/env.sh
docker-compose pull
sh deploy-edgeX.sh 
sh ./bin/run.sh -sn
...
...

↳ Query limited transmissions with specified slug and created date range
  GET http://edgex-support-notifications:48060/api/v1/transmission/slug/notice-025/start/1558653868391/end/1558654168391/5 [200 OK, 1.85KB, 13ms]
  ✓  Status code is 200
  ✓  Response time is less than 800ms
  ✓  Content-Type is present
  ✓  Response count is correct
  ✓  Content-Type is application/json
  ✓  Response body is correct
  ✓  Is valid response schema

```

**Comment by cloudxxx8** [comment]
the Allure report is clean now.  close this issue
