### ISSUE TITLE
Coredata Tests Need Device Data

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#27]
I think we need to create device data and all of the dependent entries that go with devices (profile, addressable, etc) for the coredata tests. Here's the use case:

By default in the core-data service the "MetaDataCheck" flag is set to false. When set to true, this flag causes core-data to call core-metadata in order to validate that the device Id/Name exists in the database. If it does not exist, a 404 is returned.

When the flag is set to its default (false) and I run the event tests from the core-data collection, I get 78 pass, 0 fail.

When the flag is set to true and I do the same, I get 48 pass, 7 fail. This is because there isn't any device data specified in the DataDumps/coredata folder that I can use to populate the database. Thus every call to core-metadata is returning "not found".

https://github.com/edgexfoundry/blackbox-testing/tree/master/bin/postman-test/DataDumps/coredata

**Comment by cloudxxx8** [comment]
they should be different test cases, and we need to verify all of them:

1. "MetaDataCheck" flag is false and some dependent profiles do not exist, and test can pass with appropriate data returned
2. "MetaDataCheck" flag is true and some dependent profiles do not exist, and test can pass with expected 404 status code

If we create all the dependent entries, we can't verify the behavior of "MetaDataCheck" flag
Thus, I suggest to modify the test script, instead of creating data

**Comment by weichou1229** [comment]
@tsconn23 
if want to test different configuration ,may have below solutions :
1.add another config file at edgex-go/cmd/core-data/re , but need redeploy service
or
2.add api for modify configuration

I think use api is more useful , do you have any idea ?

**Comment by tsconn23** [comment]
@weichou1229 Do you use Consul when running the blackbox tests? If so, you can go into the Consul UI and change settings then restart the given service. I agree that whatever we decide on should eventually be automated or point and click.

**Comment by weichou1229** [comment]
so , when auto test running , it's should use Consul api to change setting , then restart the service .

**Comment by jinlinGuan** [comment]
Move this issue to [edgexfoundry/edgex-taf#17](https://github.com/edgexfoundry/edgex-taf/issues/17)
