### ISSUE TITLE
CoreData test error

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/blackbox-testing#29]
here are 4 test error in blackbox-testing ,
it's happen when post new event , post new reading , put reading  
https://github.com/edgexfoundry/blackbox-testing/blob/master/bin/postman-test/collections/core-data.postman_collection.json#L361
https://github.com/edgexfoundry/blackbox-testing/blob/master/bin/postman-test/collections/core-data.postman_collection.json#L929
https://github.com/edgexfoundry/blackbox-testing/blob/master/bin/postman-test/collections/core-data.postman_collection.json#L293
https://github.com/edgexfoundry/blackbox-testing/blob/master/bin/postman-test/collections/core-data.postman_collection.json#L1068

these testing all validate the associated value descriptor is non-existent ,
but after these PR https://github.com/edgexfoundry/edgex-go/pull/247 , it can't validate value descriptor , because configuration.ValidateCheck is false .

so , do we still test the behavior of **associated value descriptor is non-existent** ?

**Comment by weichou1229** [comment]
@tsconn23

**Comment by tsconn23** [comment]
@weichou1229 Take a look at #27 where I pointed out something similar based on these flags. @cloudxxx8  suggested these be different test cases because yes, they should obviously be tested. We need to work toward a solution where it's as easy as possible to populate data, run the tests where the flag (and others like it) are false. Then possibly clean the DB and re-import, toggle the flag to true and run the other batch of tests. This can be done as a series of manual steps but we'll want to work toward scripting it somehow for ease of use.

**Comment by weichou1229** [comment]
ok ,  we can modify test script to satisfy the behavior that configuration.ValidateCheck is false . 
and write another script to test configuration.ValidateCheck is true
