### ISSUE TITLE
Jenkins job of arm64 security failed

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/blackbox-testing#302]
It seems because of the services can't connect to Mongo DB.
Mongo DB error in the console.
`04:54:33 level=ERROR ts=2019-10-24T20:48:30.998740774Z app=edgex-mongo source=main.go:57 msg="edgex-mongo failed because of: open /vault/config/assets/resp-init.json: permission denied"`

Reference jenkins job [arm64 log](https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-master/294/console).

**Comment by cloudxxx8** [comment]
add @michaelestrin and @tingyuz for awareness

**Comment by lranjbar** [comment]
The current running hypothesis is that mongo is trying to start up before vault is ready for it. This is why mongo is not starting. If you watch this job you will see that it hangs at trying to load data from mongo for 15mins+. Jenkins is merely killing the job because it is timing out in this case. 

@cloudxxx8 @tingyuz

**Comment by judehung** [comment]
By looking into the [arm64 console output](https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-fuji/12/consoleFull), I think that vault worker finished the init before edgex-mongo tried to get the access token from /vault/config/assets/resp-init.json.

> 07:02:13 level=INFO ts=**2019-11-06T22:54:09.98989947Z** app=edgex-security-secretstore-setup source=main.go:249 msg="proxy certificate pair are uploaded to secret store successfully, Vault init done successfully"

> 07:02:15 level=INFO ts=**2019-11-06T22:56:09.826156095Z** app=edgex-mongo source=main.go:32 msg="starting edgex-mongo process ..."
> 07:02:15 level=INFO ts=**2019-11-06T22:56:09.826225807Z** app=edgex-mongo source=config.go:38 msg="loading configuration considering the secret store"
> 07:02:15 level=INFO ts=**2019-11-06T22:56:09.826338141Z** app=edgex-mongo source=init.go:47 msg="config file location: res/docker/configuration.toml"
> 07:02:15 level=ERROR ts=**2019-11-06T22:56:09.828656783Z** app=edgex-mongo source=main.go:57 msg="edgex-mongo failed because of: open /vault/config/assets/resp-init.json: permission denied"



I'm setting up a Rasberry Pi arm64 to see what the file permission of /vault/config/assets/resp-init.json inside edgex-mongo container.  Hope this could give us some hints about this issue.

**Comment by judehung** [comment]
I’m able to reproduce this issue on an arm64 SBC (Rasberry Pi 3B+).  After digging into this issue, I realized that /vault/config/assets/resp-init.json has following file permission:

`-rw-------    1 root     root           649 Nov  7 08:46 resp-init.json`

However, [arm64-based edgex-mongo Dockerfile set the default user “mongodb“ to run the mongo container](https://github.com/edgexfoundry/docker-edgex-mongo/blob/fuji/cmd/Dockerfile.aarch64#L43), thus hitting the permission denied when accessing /vault/config/assets/resp-init.json inside mongo container.

For [x86-based edgex-mongo Dockerfile](https://github.com/edgexfoundry/docker-edgex-mongo/blob/fuji/cmd/Dockerfile), the default user will be "root", thus having no issue when accessing /vault/config/assets/resp-init.json.

To resolve this issue, we may have following options:

1. Update [Dockerfile.aarch64](https://github.com/edgexfoundry/docker-edgex-mongo/blob/fuji/cmd/Dockerfile.aarch64#L43) to remove `USER mongodb`, so that arm64 edgex-mongo container will be running with root.

2. Update the [Dockerfile of security-secret-store](https://github.com/edgexfoundry/security-secret-store/blob/master/Dockerfile.vault), a.k.a, vault, so that /vault/config/assets/resp-init.json could be read by non-root users, e.g. mongodb.

**Comment by anonymouse64** [comment]
> Update the Dockerfile of security-secret-store, a.k.a, vault, so that /vault/config/assets/resp-init.json could be read by non-root users, e.g. mongodb.

Strongly recommend against this option because the root token enables lots of access to Vault. 

CC @bnevis-i @tingyuz @jim-wang-intel

**Comment by bnevis-i** [comment]
> However, arm64-based edgex-mongo Dockerfile set the default user “mongodb“ to run the mongo container, thus hitting the permission denied when accessing /vault/config/assets/resp-init.json inside mongo container.

> Update Dockerfile.aarch64 to remove USER mongodb, so that arm64 edgex-mongo container will be running with root.

How about put `user: 0:0` in the docker-compose to override the user and make it work like the x86-based version?

> Update the Dockerfile of security-secret-store, a.k.a, vault, so that /vault/config/assets/resp-init.json could be read by non-root users, e.g. mongodb.

Or just make a copy of `resp-init.json` and chmod's it to the UID and GID of the mongodb user and have the mongodb container look for the copy.  The x86 version of the container would bypass any ACLs because it is root and the aarch64 version would just work.

However, this discover does have implications for the per-service Vault tokens planned for Gevenva -- it will be necessary at the outset to be able to set the owner/group of all the tokens.

**Comment by bnevis-i** [comment]
> However, this discover does have implications for the per-service Vault tokens planned for Gevenva -- it will be necessary at the outset to be able to set the owner/group of all the tokens.

Strike that last comment.  Mongodb is being replaced with Redis in Geneva, so this issue won't come up in this context.

**Comment by michaelestrin** [comment]
> Mongodb is being replaced with Redis in Geneva, so this issue won't come up in this context.

Not exactly.  MongoDB will still be around and will need to be supported.  Redis is just becoming the default.

**Comment by lranjbar** [comment]
This was triaged and resolved at the EdgeX F2F. A big thanks to all involved. 🎉 

@difince @tingyuz @tsconn23 @michaelestrin @AnthonyMBonafide @bnevis-i @jim-wang-intel @mkbhanda
